"""empty message

Revision ID: 236d4ece9dde
Revises: a6c325dd704e
Create Date: 2018-01-22 15:37:03.171755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236d4ece9dde'
down_revision = 'a6c325dd704e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'time')
    # ### end Alembic commands ###
