"""empty message

Revision ID: 7f302933e74c
Revises: c513f4f31a60
Create Date: 2018-01-22 14:58:19.469208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f302933e74c'
down_revision = 'c513f4f31a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('preview_video_url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'preview_video_url')
    # ### end Alembic commands ###
