"""empty message

Revision ID: b7ed21905046
Revises: 
Create Date: 2018-01-14 21:52:00.934163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ed21905046'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=140), nullable=True),
    sa.Column('lat', sa.String(length=64), nullable=True),
    sa.Column('lng', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_address'), 'venue', ['address'], unique=False)
    op.create_index(op.f('ix_venue_name'), 'venue', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_name'), table_name='venue')
    op.drop_index(op.f('ix_venue_address'), table_name='venue')
    op.drop_table('venue')
    # ### end Alembic commands ###
