"""empty message

Revision ID: e94e77d5bfdb
Revises: 733ab7b32c34
Create Date: 2018-01-24 22:40:27.670940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94e77d5bfdb'
down_revision = '733ab7b32c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=280),
               existing_nullable=False)
    op.alter_column('artists', 'preview_video_thumbnail',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=280),
               existing_nullable=True)
    op.alter_column('artists', 'preview_video_url',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=280),
               existing_nullable=True)
    op.alter_column('venues', 'address',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=280),
               existing_nullable=True)
    op.alter_column('venues', 'lat',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=280),
               existing_nullable=True)
    op.alter_column('venues', 'lng',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=280),
               existing_nullable=True)
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=280),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'name',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('venues', 'lng',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('venues', 'lat',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('venues', 'address',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    op.alter_column('artists', 'preview_video_url',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    op.alter_column('artists', 'preview_video_thumbnail',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
    op.alter_column('artists', 'name',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
    # ### end Alembic commands ###
